const citySample = [
	{
		Version: 1,
		Key: "332328",
		Type: "City",
		Rank: 55,
		LocalizedName: "Sanford",
		EnglishName: "Sanford",
		PrimaryPostalCode: "32771",
		Region: {
			ID: "NAM",
			LocalizedName: "North America",
			EnglishName: "North America",
		},
		Country: {
			ID: "US",
			LocalizedName: "United States",
			EnglishName: "United States",
		},
		AdministrativeArea: {
			ID: "FL",
			LocalizedName: "Florida",
			EnglishName: "Florida",
			Level: 1,
			LocalizedType: "State",
			EnglishType: "State",
			CountryID: "US",
		},
		TimeZone: {
			Code: "EDT",
			Name: "America/New_York",
			GmtOffset: -4.0,
			IsDaylightSaving: true,
			NextOffsetChange: "2020-11-01T06:00:00Z",
		},
		GeoPosition: {
			Latitude: 28.801,
			Longitude: -81.273,
			Elevation: {
				Metric: {
					Value: 11.0,
					Unit: "m",
					UnitType: 5,
				},
				Imperial: {
					Value: 36.0,
					Unit: "ft",
					UnitType: 0,
				},
			},
		},
		IsAlias: false,
		SupplementalAdminAreas: [
			{
				Level: 2,
				LocalizedName: "Seminole",
				EnglishName: "Seminole",
			},
		],
		DataSets: [
			"AirQualityCurrentConditions",
			"AirQualityForecasts",
			"Alerts",
			"DailyAirQualityForecast",
			"DailyPollenForecast",
			"ForecastConfidence",
			"FutureRadar",
			"MinuteCast",
			"Radar",
		],
	},
	{
		Version: 1,
		Key: "334826",
		Type: "City",
		Rank: 55,
		LocalizedName: "Sanford",
		EnglishName: "Sanford",
		PrimaryPostalCode: "27330",
		Region: {
			ID: "NAM",
			LocalizedName: "North America",
			EnglishName: "North America",
		},
		Country: {
			ID: "US",
			LocalizedName: "United States",
			EnglishName: "United States",
		},
		AdministrativeArea: {
			ID: "NC",
			LocalizedName: "North Carolina",
			EnglishName: "North Carolina",
			Level: 1,
			LocalizedType: "State",
			EnglishType: "State",
			CountryID: "US",
		},
		TimeZone: {
			Code: "EDT",
			Name: "America/New_York",
			GmtOffset: -4.0,
			IsDaylightSaving: true,
			NextOffsetChange: "2020-11-01T06:00:00Z",
		},
		GeoPosition: {
			Latitude: 35.48,
			Longitude: -79.18,
			Elevation: {
				Metric: {
					Value: 114.0,
					Unit: "m",
					UnitType: 5,
				},
				Imperial: {
					Value: 373.0,
					Unit: "ft",
					UnitType: 0,
				},
			},
		},
		IsAlias: false,
		SupplementalAdminAreas: [
			{
				Level: 2,
				LocalizedName: "Lee",
				EnglishName: "Lee",
			},
		],
		DataSets: [
			"AirQualityCurrentConditions",
			"AirQualityForecasts",
			"Alerts",
			"DailyAirQualityForecast",
			"DailyPollenForecast",
			"ForecastConfidence",
			"FutureRadar",
			"MinuteCast",
			"Radar",
		],
	},
	{
		Version: 1,
		Key: "338526",
		Type: "City",
		Rank: 65,
		LocalizedName: "Sanford",
		EnglishName: "Sanford",
		PrimaryPostalCode: "04073",
		Region: {
			ID: "NAM",
			LocalizedName: "North America",
			EnglishName: "North America",
		},
		Country: {
			ID: "US",
			LocalizedName: "United States",
			EnglishName: "United States",
		},
		AdministrativeArea: {
			ID: "ME",
			LocalizedName: "Maine",
			EnglishName: "Maine",
			Level: 1,
			LocalizedType: "State",
			EnglishType: "State",
			CountryID: "US",
		},
		TimeZone: {
			Code: "EDT",
			Name: "America/New_York",
			GmtOffset: -4.0,
			IsDaylightSaving: true,
			NextOffsetChange: "2020-11-01T06:00:00Z",
		},
		GeoPosition: {
			Latitude: 43.44,
			Longitude: -70.78,
			Elevation: {
				Metric: {
					Value: 113.0,
					Unit: "m",
					UnitType: 5,
				},
				Imperial: {
					Value: 370.0,
					Unit: "ft",
					UnitType: 0,
				},
			},
		},
		IsAlias: false,
		SupplementalAdminAreas: [
			{
				Level: 2,
				LocalizedName: "York",
				EnglishName: "York",
			},
		],
		DataSets: [
			"AirQualityCurrentConditions",
			"AirQualityForecasts",
			"Alerts",
			"DailyAirQualityForecast",
			"DailyPollenForecast",
			"ForecastConfidence",
			"FutureRadar",
			"MinuteCast",
			"Radar",
		],
	},
	{
		Version: 1,
		Key: "341009",
		Type: "City",
		Rank: 85,
		LocalizedName: "Sanford",
		EnglishName: "Sanford",
		PrimaryPostalCode: "79078",
		Region: {
			ID: "NAM",
			LocalizedName: "North America",
			EnglishName: "North America",
		},
		Country: {
			ID: "US",
			LocalizedName: "United States",
			EnglishName: "United States",
		},
		AdministrativeArea: {
			ID: "TX",
			LocalizedName: "Texas",
			EnglishName: "Texas",
			Level: 1,
			LocalizedType: "State",
			EnglishType: "State",
			CountryID: "US",
		},
		TimeZone: {
			Code: "CDT",
			Name: "America/Chicago",
			GmtOffset: -5.0,
			IsDaylightSaving: true,
			NextOffsetChange: "2020-11-01T07:00:00Z",
		},
		GeoPosition: {
			Latitude: 35.702,
			Longitude: -101.535,
			Elevation: {
				Metric: {
					Value: 892.0,
					Unit: "m",
					UnitType: 5,
				},
				Imperial: {
					Value: 2925.0,
					Unit: "ft",
					UnitType: 0,
				},
			},
		},
		IsAlias: false,
		SupplementalAdminAreas: [
			{
				Level: 2,
				LocalizedName: "Hutchinson",
				EnglishName: "Hutchinson",
			},
		],
		DataSets: [
			"AirQualityCurrentConditions",
			"AirQualityForecasts",
			"Alerts",
			"DailyAirQualityForecast",
			"DailyPollenForecast",
			"ForecastConfidence",
			"FutureRadar",
			"MinuteCast",
			"Radar",
		],
	},
	{
		Version: 1,
		Key: "2211690",
		Type: "City",
		Rank: 85,
		LocalizedName: "Sanford",
		EnglishName: "Sanford",
		PrimaryPostalCode: "48657",
		Region: {
			ID: "NAM",
			LocalizedName: "North America",
			EnglishName: "North America",
		},
		Country: {
			ID: "US",
			LocalizedName: "United States",
			EnglishName: "United States",
		},
		AdministrativeArea: {
			ID: "MI",
			LocalizedName: "Michigan",
			EnglishName: "Michigan",
			Level: 1,
			LocalizedType: "State",
			EnglishType: "State",
			CountryID: "US",
		},
		TimeZone: {
			Code: "EDT",
			Name: "America/Detroit",
			GmtOffset: -4.0,
			IsDaylightSaving: true,
			NextOffsetChange: "2020-11-01T06:00:00Z",
		},
		GeoPosition: {
			Latitude: 43.673,
			Longitude: -84.381,
			Elevation: {
				Metric: {
					Value: 191.0,
					Unit: "m",
					UnitType: 5,
				},
				Imperial: {
					Value: 626.0,
					Unit: "ft",
					UnitType: 0,
				},
			},
		},
		IsAlias: false,
		SupplementalAdminAreas: [
			{
				Level: 2,
				LocalizedName: "Midland",
				EnglishName: "Midland",
			},
		],
		DataSets: [
			"AirQualityCurrentConditions",
			"AirQualityForecasts",
			"Alerts",
			"DailyAirQualityForecast",
			"DailyPollenForecast",
			"ForecastConfidence",
			"FutureRadar",
			"MinuteCast",
			"Radar",
		],
	},
	{
		Version: 1,
		Key: "2207589",
		Type: "City",
		Rank: 85,
		LocalizedName: "Sanford",
		EnglishName: "Sanford",
		PrimaryPostalCode: "81151",
		Region: {
			ID: "NAM",
			LocalizedName: "North America",
			EnglishName: "North America",
		},
		Country: {
			ID: "US",
			LocalizedName: "United States",
			EnglishName: "United States",
		},
		AdministrativeArea: {
			ID: "CO",
			LocalizedName: "Colorado",
			EnglishName: "Colorado",
			Level: 1,
			LocalizedType: "State",
			EnglishType: "State",
			CountryID: "US",
		},
		TimeZone: {
			Code: "MDT",
			Name: "America/Denver",
			GmtOffset: -6.0,
			IsDaylightSaving: true,
			NextOffsetChange: "2020-11-01T08:00:00Z",
		},
		GeoPosition: {
			Latitude: 37.258,
			Longitude: -105.905,
			Elevation: {
				Metric: {
					Value: 2295.0,
					Unit: "m",
					UnitType: 5,
				},
				Imperial: {
					Value: 7530.0,
					Unit: "ft",
					UnitType: 0,
				},
			},
		},
		IsAlias: false,
		SupplementalAdminAreas: [
			{
				Level: 2,
				LocalizedName: "Conejos",
				EnglishName: "Conejos",
			},
		],
		DataSets: [
			"AirQualityCurrentConditions",
			"AirQualityForecasts",
			"Alerts",
			"DailyAirQualityForecast",
			"DailyPollenForecast",
			"ForecastConfidence",
			"FutureRadar",
			"MinuteCast",
			"Radar",
		],
	},
	{
		Version: 1,
		Key: "2172350",
		Type: "City",
		Rank: 85,
		LocalizedName: "Sanford",
		EnglishName: "Sanford",
		PrimaryPostalCode: "23426",
		Region: {
			ID: "NAM",
			LocalizedName: "North America",
			EnglishName: "North America",
		},
		Country: {
			ID: "US",
			LocalizedName: "United States",
			EnglishName: "United States",
		},
		AdministrativeArea: {
			ID: "VA",
			LocalizedName: "Virginia",
			EnglishName: "Virginia",
			Level: 1,
			LocalizedType: "State",
			EnglishType: "State",
			CountryID: "US",
		},
		TimeZone: {
			Code: "EDT",
			Name: "America/New_York",
			GmtOffset: -4.0,
			IsDaylightSaving: true,
			NextOffsetChange: "2020-11-01T06:00:00Z",
		},
		GeoPosition: {
			Latitude: 37.925,
			Longitude: -75.664,
			Elevation: {
				Metric: {
					Value: 2.0,
					Unit: "m",
					UnitType: 5,
				},
				Imperial: {
					Value: 6.0,
					Unit: "ft",
					UnitType: 0,
				},
			},
		},
		IsAlias: false,
		SupplementalAdminAreas: [
			{
				Level: 2,
				LocalizedName: "Accomack",
				EnglishName: "Accomack",
			},
		],
		DataSets: [
			"AirQualityCurrentConditions",
			"AirQualityForecasts",
			"Alerts",
			"DailyAirQualityForecast",
			"DailyPollenForecast",
			"ForecastConfidence",
			"FutureRadar",
			"MinuteCast",
			"Radar",
		],
	},
	{
		Version: 1,
		Key: "3391131",
		Type: "City",
		Rank: 85,
		LocalizedName: "Sanford",
		EnglishName: "Sanford",
		PrimaryPostalCode: "G0A",
		Region: {
			ID: "NAM",
			LocalizedName: "North America",
			EnglishName: "North America",
		},
		Country: {
			ID: "CA",
			LocalizedName: "Canada",
			EnglishName: "Canada",
		},
		AdministrativeArea: {
			ID: "QC",
			LocalizedName: "Quebec",
			EnglishName: "Quebec",
			Level: 1,
			LocalizedType: "Province",
			EnglishType: "Province",
			CountryID: "CA",
		},
		TimeZone: {
			Code: "EDT",
			Name: "America/Montreal",
			GmtOffset: -4.0,
			IsDaylightSaving: true,
			NextOffsetChange: "2020-11-01T06:00:00Z",
		},
		GeoPosition: {
			Latitude: 47.495,
			Longitude: -72.176,
			Elevation: {
				Metric: {
					Value: 366.0,
					Unit: "m",
					UnitType: 5,
				},
				Imperial: {
					Value: 1200.0,
					Unit: "ft",
					UnitType: 0,
				},
			},
		},
		IsAlias: false,
		SupplementalAdminAreas: [
			{
				Level: 2,
				LocalizedName: "La Tuque",
				EnglishName: "La Tuque",
			},
		],
		DataSets: [
			"AirQualityCurrentConditions",
			"AirQualityForecasts",
			"Alerts",
			"ForecastConfidence",
			"FutureRadar",
			"MinuteCast",
			"Radar",
		],
	},
	{
		Version: 1,
		Key: "2289033",
		Type: "City",
		Rank: 85,
		LocalizedName: "Sanford",
		EnglishName: "Sanford",
		PrimaryPostalCode: "R0G",
		Region: {
			ID: "NAM",
			LocalizedName: "North America",
			EnglishName: "North America",
		},
		Country: {
			ID: "CA",
			LocalizedName: "Canada",
			EnglishName: "Canada",
		},
		AdministrativeArea: {
			ID: "MB",
			LocalizedName: "Manitoba",
			EnglishName: "Manitoba",
			Level: 1,
			LocalizedType: "Province",
			EnglishType: "Province",
			CountryID: "CA",
		},
		TimeZone: {
			Code: "CDT",
			Name: "America/Winnipeg",
			GmtOffset: -5.0,
			IsDaylightSaving: true,
			NextOffsetChange: "2020-11-01T07:00:00Z",
		},
		GeoPosition: {
			Latitude: 49.679,
			Longitude: -97.436,
			Elevation: {
				Metric: {
					Value: 236.0,
					Unit: "m",
					UnitType: 5,
				},
				Imperial: {
					Value: 774.0,
					Unit: "ft",
					UnitType: 0,
				},
			},
		},
		IsAlias: false,
		SupplementalAdminAreas: [],
		DataSets: [
			"AirQualityCurrentConditions",
			"AirQualityForecasts",
			"Alerts",
			"ForecastConfidence",
			"FutureRadar",
			"MinuteCast",
			"Radar",
		],
	},
	{
		Version: 1,
		Key: "11205",
		Type: "City",
		Rank: 85,
		LocalizedName: "Sanford",
		EnglishName: "Sanford",
		PrimaryPostalCode: "",
		Region: {
			ID: "SAM",
			LocalizedName: "South America",
			EnglishName: "South America",
		},
		Country: {
			ID: "AR",
			LocalizedName: "Argentina",
			EnglishName: "Argentina",
		},
		AdministrativeArea: {
			ID: "S",
			LocalizedName: "Santa Fe",
			EnglishName: "Santa Fe",
			Level: 1,
			LocalizedType: "Province",
			EnglishType: "Province",
			CountryID: "AR",
		},
		TimeZone: {
			Code: "ART",
			Name: "America/Argentina/Cordoba",
			GmtOffset: -3.0,
			IsDaylightSaving: false,
			NextOffsetChange: null,
		},
		GeoPosition: {
			Latitude: -33.145,
			Longitude: -61.28,
			Elevation: {
				Metric: {
					Value: 84.0,
					Unit: "m",
					UnitType: 5,
				},
				Imperial: {
					Value: 275.0,
					Unit: "ft",
					UnitType: 0,
				},
			},
		},
		IsAlias: false,
		SupplementalAdminAreas: [],
		DataSets: ["AirQualityCurrentConditions", "AirQualityForecasts", "Radar"],
	},
	{
		Version: 1,
		Key: "2231853",
		Type: "City",
		Rank: 85,
		LocalizedName: "Sanford",
		EnglishName: "Sanford",
		PrimaryPostalCode: "36421",
		Region: {
			ID: "NAM",
			LocalizedName: "North America",
			EnglishName: "North America",
		},
		Country: {
			ID: "US",
			LocalizedName: "United States",
			EnglishName: "United States",
		},
		AdministrativeArea: {
			ID: "AL",
			LocalizedName: "Alabama",
			EnglishName: "Alabama",
			Level: 1,
			LocalizedType: "State",
			EnglishType: "State",
			CountryID: "US",
		},
		TimeZone: {
			Code: "CDT",
			Name: "America/Chicago",
			GmtOffset: -5.0,
			IsDaylightSaving: true,
			NextOffsetChange: "2020-11-01T07:00:00Z",
		},
		GeoPosition: {
			Latitude: 31.298,
			Longitude: -86.389,
			Elevation: {
				Metric: {
					Value: 91.0,
					Unit: "m",
					UnitType: 5,
				},
				Imperial: {
					Value: 298.0,
					Unit: "ft",
					UnitType: 0,
				},
			},
		},
		IsAlias: false,
		SupplementalAdminAreas: [
			{
				Level: 2,
				LocalizedName: "Covington",
				EnglishName: "Covington",
			},
		],
		DataSets: [
			"AirQualityCurrentConditions",
			"AirQualityForecasts",
			"Alerts",
			"DailyAirQualityForecast",
			"DailyPollenForecast",
			"ForecastConfidence",
			"FutureRadar",
			"MinuteCast",
			"Radar",
		],
	},
	{
		Version: 1,
		Key: "2128772",
		Type: "City",
		Rank: 285,
		LocalizedName: "Sanford",
		EnglishName: "Sanford",
		PrimaryPostalCode: "13754",
		Region: {
			ID: "NAM",
			LocalizedName: "North America",
			EnglishName: "North America",
		},
		Country: {
			ID: "US",
			LocalizedName: "United States",
			EnglishName: "United States",
		},
		AdministrativeArea: {
			ID: "NY",
			LocalizedName: "New York",
			EnglishName: "New York",
			Level: 1,
			LocalizedType: "State",
			EnglishType: "State",
			CountryID: "US",
		},
		TimeZone: {
			Code: "EDT",
			Name: "America/New_York",
			GmtOffset: -4.0,
			IsDaylightSaving: true,
			NextOffsetChange: "2020-11-01T06:00:00Z",
		},
		GeoPosition: {
			Latitude: 42.092,
			Longitude: -75.482,
			Elevation: {
				Metric: {
					Value: 364.0,
					Unit: "m",
					UnitType: 5,
				},
				Imperial: {
					Value: 1193.0,
					Unit: "ft",
					UnitType: 0,
				},
			},
		},
		IsAlias: false,
		SupplementalAdminAreas: [
			{
				Level: 2,
				LocalizedName: "Broome",
				EnglishName: "Broome",
			},
		],
		DataSets: [
			"AirQualityCurrentConditions",
			"AirQualityForecasts",
			"Alerts",
			"DailyAirQualityForecast",
			"DailyPollenForecast",
			"ForecastConfidence",
			"FutureRadar",
			"MinuteCast",
			"Radar",
		],
	},
	{
		Version: 1,
		Key: "2236233",
		Type: "City",
		Rank: 385,
		LocalizedName: "Sanford",
		EnglishName: "Sanford",
		PrimaryPostalCode: "37370",
		Region: {
			ID: "NAM",
			LocalizedName: "North America",
			EnglishName: "North America",
		},
		Country: {
			ID: "US",
			LocalizedName: "United States",
			EnglishName: "United States",
		},
		AdministrativeArea: {
			ID: "TN",
			LocalizedName: "Tennessee",
			EnglishName: "Tennessee",
			Level: 1,
			LocalizedType: "State",
			EnglishType: "State",
			CountryID: "US",
		},
		TimeZone: {
			Code: "EDT",
			Name: "America/New_York",
			GmtOffset: -4.0,
			IsDaylightSaving: true,
			NextOffsetChange: "2020-11-01T06:00:00Z",
		},
		GeoPosition: {
			Latitude: 35.342,
			Longitude: -84.72,
			Elevation: {
				Metric: {
					Value: 239.0,
					Unit: "m",
					UnitType: 5,
				},
				Imperial: {
					Value: 783.0,
					Unit: "ft",
					UnitType: 0,
				},
			},
		},
		IsAlias: false,
		SupplementalAdminAreas: [
			{
				Level: 2,
				LocalizedName: "McMinn",
				EnglishName: "McMinn",
			},
		],
		DataSets: [
			"AirQualityCurrentConditions",
			"AirQualityForecasts",
			"Alerts",
			"DailyAirQualityForecast",
			"DailyPollenForecast",
			"ForecastConfidence",
			"FutureRadar",
			"MinuteCast",
			"Radar",
		],
	},
	{
		Version: 1,
		Key: "2153324",
		Type: "City",
		Rank: 385,
		LocalizedName: "Sanford",
		EnglishName: "Sanford",
		PrimaryPostalCode: "31815",
		Region: {
			ID: "NAM",
			LocalizedName: "North America",
			EnglishName: "North America",
		},
		Country: {
			ID: "US",
			LocalizedName: "United States",
			EnglishName: "United States",
		},
		AdministrativeArea: {
			ID: "GA",
			LocalizedName: "Georgia",
			EnglishName: "Georgia",
			Level: 1,
			LocalizedType: "State",
			EnglishType: "State",
			CountryID: "US",
		},
		TimeZone: {
			Code: "EDT",
			Name: "America/New_York",
			GmtOffset: -4.0,
			IsDaylightSaving: true,
			NextOffsetChange: "2020-11-01T06:00:00Z",
		},
		GeoPosition: {
			Latitude: 31.98,
			Longitude: -84.944,
			Elevation: {
				Metric: {
					Value: 134.0,
					Unit: "m",
					UnitType: 5,
				},
				Imperial: {
					Value: 439.0,
					Unit: "ft",
					UnitType: 0,
				},
			},
		},
		IsAlias: false,
		SupplementalAdminAreas: [
			{
				Level: 2,
				LocalizedName: "Stewart",
				EnglishName: "Stewart",
			},
		],
		DataSets: [
			"AirQualityCurrentConditions",
			"AirQualityForecasts",
			"Alerts",
			"DailyAirQualityForecast",
			"DailyPollenForecast",
			"ForecastConfidence",
			"FutureRadar",
			"MinuteCast",
			"Radar",
		],
	},
	{
		Version: 1,
		Key: "2153325",
		Type: "City",
		Rank: 385,
		LocalizedName: "Sanford",
		EnglishName: "Sanford",
		PrimaryPostalCode: "30646",
		Region: {
			ID: "NAM",
			LocalizedName: "North America",
			EnglishName: "North America",
		},
		Country: {
			ID: "US",
			LocalizedName: "United States",
			EnglishName: "United States",
		},
		AdministrativeArea: {
			ID: "GA",
			LocalizedName: "Georgia",
			EnglishName: "Georgia",
			Level: 1,
			LocalizedType: "State",
			EnglishType: "State",
			CountryID: "US",
		},
		TimeZone: {
			Code: "EDT",
			Name: "America/New_York",
			GmtOffset: -4.0,
			IsDaylightSaving: true,
			NextOffsetChange: "2020-11-01T06:00:00Z",
		},
		GeoPosition: {
			Latitude: 34.079,
			Longitude: -83.348,
			Elevation: {
				Metric: {
					Value: 255.0,
					Unit: "m",
					UnitType: 5,
				},
				Imperial: {
					Value: 836.0,
					Unit: "ft",
					UnitType: 0,
				},
			},
		},
		IsAlias: false,
		SupplementalAdminAreas: [
			{
				Level: 2,
				LocalizedName: "Madison",
				EnglishName: "Madison",
			},
		],
		DataSets: [
			"AirQualityCurrentConditions",
			"AirQualityForecasts",
			"Alerts",
			"DailyAirQualityForecast",
			"DailyPollenForecast",
			"ForecastConfidence",
			"FutureRadar",
			"MinuteCast",
			"Radar",
		],
	},
	{
		Version: 1,
		Key: "2148721",
		Type: "City",
		Rank: 385,
		LocalizedName: "Sanford",
		EnglishName: "Sanford",
		PrimaryPostalCode: "67550",
		Region: {
			ID: "NAM",
			LocalizedName: "North America",
			EnglishName: "North America",
		},
		Country: {
			ID: "US",
			LocalizedName: "United States",
			EnglishName: "United States",
		},
		AdministrativeArea: {
			ID: "KS",
			LocalizedName: "Kansas",
			EnglishName: "Kansas",
			Level: 1,
			LocalizedType: "State",
			EnglishType: "State",
			CountryID: "US",
		},
		TimeZone: {
			Code: "CDT",
			Name: "America/Chicago",
			GmtOffset: -5.0,
			IsDaylightSaving: true,
			NextOffsetChange: "2020-11-01T07:00:00Z",
		},
		GeoPosition: {
			Latitude: 38.181,
			Longitude: -99.314,
			Elevation: {
				Metric: {
					Value: 626.0,
					Unit: "m",
					UnitType: 5,
				},
				Imperial: {
					Value: 2053.0,
					Unit: "ft",
					UnitType: 0,
				},
			},
		},
		IsAlias: false,
		SupplementalAdminAreas: [
			{
				Level: 2,
				LocalizedName: "Pawnee",
				EnglishName: "Pawnee",
			},
		],
		DataSets: [
			"AirQualityCurrentConditions",
			"AirQualityForecasts",
			"Alerts",
			"DailyAirQualityForecast",
			"DailyPollenForecast",
			"ForecastConfidence",
			"FutureRadar",
			"MinuteCast",
			"Radar",
		],
	},
	{
		Version: 1,
		Key: "2120392",
		Type: "City",
		Rank: 385,
		LocalizedName: "Sanford",
		EnglishName: "Sanford",
		PrimaryPostalCode: "20902",
		Region: {
			ID: "NAM",
			LocalizedName: "North America",
			EnglishName: "North America",
		},
		Country: {
			ID: "US",
			LocalizedName: "United States",
			EnglishName: "United States",
		},
		AdministrativeArea: {
			ID: "MD",
			LocalizedName: "Maryland",
			EnglishName: "Maryland",
			Level: 1,
			LocalizedType: "State",
			EnglishType: "State",
			CountryID: "US",
		},
		TimeZone: {
			Code: "EDT",
			Name: "America/New_York",
			GmtOffset: -4.0,
			IsDaylightSaving: true,
			NextOffsetChange: "2020-11-01T06:00:00Z",
		},
		GeoPosition: {
			Latitude: 39.019,
			Longitude: -77.041,
			Elevation: {
				Metric: {
					Value: 105.0,
					Unit: "m",
					UnitType: 5,
				},
				Imperial: {
					Value: 344.0,
					Unit: "ft",
					UnitType: 0,
				},
			},
		},
		IsAlias: false,
		SupplementalAdminAreas: [
			{
				Level: 2,
				LocalizedName: "Montgomery",
				EnglishName: "Montgomery",
			},
		],
		DataSets: [
			"AirQualityCurrentConditions",
			"AirQualityForecasts",
			"Alerts",
			"DailyAirQualityForecast",
			"DailyPollenForecast",
			"ForecastConfidence",
			"FutureRadar",
			"MinuteCast",
			"Radar",
		],
	},
	{
		Version: 1,
		Key: "2159980",
		Type: "City",
		Rank: 385,
		LocalizedName: "Sanford",
		EnglishName: "Sanford",
		PrimaryPostalCode: "39479",
		Region: {
			ID: "NAM",
			LocalizedName: "North America",
			EnglishName: "North America",
		},
		Country: {
			ID: "US",
			LocalizedName: "United States",
			EnglishName: "United States",
		},
		AdministrativeArea: {
			ID: "MS",
			LocalizedName: "Mississippi",
			EnglishName: "Mississippi",
			Level: 1,
			LocalizedType: "State",
			EnglishType: "State",
			CountryID: "US",
		},
		TimeZone: {
			Code: "CDT",
			Name: "America/Chicago",
			GmtOffset: -5.0,
			IsDaylightSaving: true,
			NextOffsetChange: "2020-11-01T07:00:00Z",
		},
		GeoPosition: {
			Latitude: 31.487,
			Longitude: -89.427,
			Elevation: {
				Metric: {
					Value: 63.0,
					Unit: "m",
					UnitType: 5,
				},
				Imperial: {
					Value: 206.0,
					Unit: "ft",
					UnitType: 0,
				},
			},
		},
		IsAlias: false,
		SupplementalAdminAreas: [
			{
				Level: 2,
				LocalizedName: "Covington",
				EnglishName: "Covington",
			},
		],
		DataSets: [
			"AirQualityCurrentConditions",
			"AirQualityForecasts",
			"Alerts",
			"DailyAirQualityForecast",
			"DailyPollenForecast",
			"ForecastConfidence",
			"FutureRadar",
			"MinuteCast",
			"Radar",
		],
	},
	{
		Version: 1,
		Key: "2171187",
		Type: "City",
		Rank: 385,
		LocalizedName: "Sanford",
		EnglishName: "Sanford",
		PrimaryPostalCode: "14754",
		Region: {
			ID: "NAM",
			LocalizedName: "North America",
			EnglishName: "North America",
		},
		Country: {
			ID: "US",
			LocalizedName: "United States",
			EnglishName: "United States",
		},
		AdministrativeArea: {
			ID: "NY",
			LocalizedName: "New York",
			EnglishName: "New York",
			Level: 1,
			LocalizedType: "State",
			EnglishType: "State",
			CountryID: "US",
		},
		TimeZone: {
			Code: "EDT",
			Name: "America/New_York",
			GmtOffset: -4.0,
			IsDaylightSaving: true,
			NextOffsetChange: "2020-11-01T06:00:00Z",
		},
		GeoPosition: {
			Latitude: 42.015,
			Longitude: -78.236,
			Elevation: {
				Metric: {
					Value: 508.0,
					Unit: "m",
					UnitType: 5,
				},
				Imperial: {
					Value: 1666.0,
					Unit: "ft",
					UnitType: 0,
				},
			},
		},
		IsAlias: false,
		SupplementalAdminAreas: [
			{
				Level: 2,
				LocalizedName: "Allegany",
				EnglishName: "Allegany",
			},
		],
		DataSets: [
			"AirQualityCurrentConditions",
			"AirQualityForecasts",
			"Alerts",
			"DailyAirQualityForecast",
			"DailyPollenForecast",
			"ForecastConfidence",
			"FutureRadar",
			"MinuteCast",
			"Radar",
		],
	},
	{
		Version: 1,
		Key: "2183608",
		Type: "City",
		Rank: 385,
		LocalizedName: "Sanford",
		EnglishName: "Sanford",
		PrimaryPostalCode: "16340",
		Region: {
			ID: "NAM",
			LocalizedName: "North America",
			EnglishName: "North America",
		},
		Country: {
			ID: "US",
			LocalizedName: "United States",
			EnglishName: "United States",
		},
		AdministrativeArea: {
			ID: "PA",
			LocalizedName: "Pennsylvania",
			EnglishName: "Pennsylvania",
			Level: 1,
			LocalizedType: "State",
			EnglishType: "State",
			CountryID: "US",
		},
		TimeZone: {
			Code: "EDT",
			Name: "America/New_York",
			GmtOffset: -4.0,
			IsDaylightSaving: true,
			NextOffsetChange: "2020-11-01T06:00:00Z",
		},
		GeoPosition: {
			Latitude: 41.77,
			Longitude: -79.536,
			Elevation: {
				Metric: {
					Value: 516.0,
					Unit: "m",
					UnitType: 5,
				},
				Imperial: {
					Value: 1692.0,
					Unit: "ft",
					UnitType: 0,
				},
			},
		},
		IsAlias: false,
		SupplementalAdminAreas: [
			{
				Level: 2,
				LocalizedName: "Warren",
				EnglishName: "Warren",
			},
		],
		DataSets: [
			"AirQualityCurrentConditions",
			"AirQualityForecasts",
			"Alerts",
			"DailyAirQualityForecast",
			"DailyPollenForecast",
			"ForecastConfidence",
			"FutureRadar",
			"MinuteCast",
			"Radar",
		],
	},
	{
		Version: 1,
		Key: "2152090",
		Type: "City",
		Rank: 385,
		LocalizedName: "Sanford",
		EnglishName: "Sanford",
		PrimaryPostalCode: "26554",
		Region: {
			ID: "NAM",
			LocalizedName: "North America",
			EnglishName: "North America",
		},
		Country: {
			ID: "US",
			LocalizedName: "United States",
			EnglishName: "United States",
		},
		AdministrativeArea: {
			ID: "WV",
			LocalizedName: "West Virginia",
			EnglishName: "West Virginia",
			Level: 1,
			LocalizedType: "State",
			EnglishType: "State",
			CountryID: "US",
		},
		TimeZone: {
			Code: "EDT",
			Name: "America/New_York",
			GmtOffset: -4.0,
			IsDaylightSaving: true,
			NextOffsetChange: "2020-11-01T06:00:00Z",
		},
		GeoPosition: {
			Latitude: 39.52,
			Longitude: -80.127,
			Elevation: {
				Metric: {
					Value: 310.0,
					Unit: "m",
					UnitType: 5,
				},
				Imperial: {
					Value: 1016.0,
					Unit: "ft",
					UnitType: 0,
				},
			},
		},
		IsAlias: false,
		SupplementalAdminAreas: [
			{
				Level: 2,
				LocalizedName: "Marion",
				EnglishName: "Marion",
			},
		],
		DataSets: [
			"AirQualityCurrentConditions",
			"AirQualityForecasts",
			"Alerts",
			"DailyAirQualityForecast",
			"DailyPollenForecast",
			"ForecastConfidence",
			"FutureRadar",
			"MinuteCast",
			"Radar",
		],
	},
];

export default citySample;
